
# language: node_js
# node_js:
#   - "node" 

language: node_js

node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - node

notifications:
  email: false

# if using Ubuntu 16 need this library
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  # install dependencies and check that Cypress can run
  override:
    - npm ci
    - npm run cy:verify

script:
  # start server in the background
  - npm start &
  # run all Cypress tests and record on the dashboard
  - npm run cy:run
  # after all tests finish running we need
  # to kill all background jobs (like "npm start &")
  # this avoids flake in Travis jobs
  - kill $(jobs -p) || true
# deploy:
#   provider: heroku
#     api_key:
#     secure: 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
#     app: the-film-vault
#     skip_cleanup: true
